name: flutter_todos
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc:
    path: ../../packages/bloc
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../packages/flutter_bloc
  path_provider: ^2.0.3

dependency_overrides:
  bloc:
    path: ../../packages/bloc
  flutter_bloc:
    path: ../../packages/flutter_bloc
  todos_app_core:
    git:
      url: https://github.com/jeroen-meijer/flutter_architecture_samples
      path: todos_app_core
      ref: feat/todos-nnbd
  todos_repository_core:
    git:
      url: https://github.com/jeroen-meijer/flutter_architecture_samples
      path: todos_repository_core
      ref: feat/todos-nnbd
  todos_repository_simple:
    git:
      url: https://github.com/jeroen-meijer/flutter_architecture_samples
      path: todos_repository_simple
      ref: feat/todos-nnbd

dev_dependencies:
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
